## every time that we push some code to github, travis will run this file to tell us if our test suit succeded or failed
sudo: required
services:
  - docker

before_install:
  # setup that needs to run either before the test suit or the deploy process
  - docker build -t fabi0brito/docker-react -f Dockerfile.dev .

script:
  # testing the application
  # status code 0 means that everything went successfully
  - docker run fabi0brito/docker-react npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-398599148408"
  bucket_path: "docker-react"
  on: 
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
      secure: "$AWS_SECRET_KEY"